title: Digital Resume
author: Brendan Devlin
email: Donttestturing@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 I am forever fascinated with new knowledge, and I am pleased that will never end 

# social links
twitter_username: your-twitter-handle
github_username:  Donttestturing

show_excerpts: true # set to false to remove excerpts on the homepage
